SCARF
=====
Ted Toal <twtoal@ucdavis.edu>
Version v0.0, Aug 2015

The BradyLab/SCARF GitHub repository contains code and documentation for the
software package called *SCARF* (SCAR Finder).

*SCARF* analyzes two or more genomes
for length-polymorphic regions bounded by unique sequences, and designs PCR
primers within these sequences. The primers can be used to amplify the region
from genomic DNA of any of the species used to create the markers, and the
amplicon size will indicate which species the DNA came from - a *SCAR* marker.

*SCAR* stands for _Sequence Characterized Amplified Regions_.

Download, Installation, and Running
-----------------------------------

Installation instructions are for Mac OSX. For other systems you are on your own,
but please take copious notes and send them to me, and I'll update these instructions.

.*To download SCARF files:*
. Browse to https://github.com/BradyLab/SCARF
. In upper-left area of screen, find drop-down box Branch:master, click to open it,
and choose the "release" branch.
. At bottom of right column on screen, click "Download ZIP" and choose a place to
put it on your computer.
. Unzip the zip file on your computer.
. Rename the unzipped folder from "SCARF-release" to just "SCARF".

.*To install SCARF:*
* Look inside the downloaded SCARF folder on your computer for file INSTALL.asciidoc
and open it with a NotePad or TextEdit or other ASCII text editor and follow the
installation instructions.

.*To run SCARF to generate markers after installation:*
* Find file RUN.asciidoc in the SCARF folder on your computer and open it and
follow the instructions.

*For help, contact Ted Toal, twtoal@ucdavis.edu*

References
----------

.SCAR markers were defined here:

[bibliography]
- [[[Paran]]], I., and R. W. Michelmore. 'Development of reliable PCR-based markers
linked to downy mildew resistance genes in lettuce.' Theoretical and Applied
Genetics 85.8 (1993): 985-993.

.The SCARF software is described in:

[bibliography]
- [[[Toal]]], T., and . 'SCARF: In silico K-mer-based Pipeline Finds Candidate
SCAR Genomic Markers and PCR Primers using NGS Data and Tomato Test Case'
(Publication in process)
