SCARF
=====
Ted Toal <twtoal@ucdavis.edu>
v0.0, Aug 2015

The BradyLab/SCARF GitHub repository contains code and documentation for the
software package called SCARF (SCAR Finder).

*SCAR stands for _Sequence Characterized Amplified Regions_.*

SCARF analyzes two or more genomes
for length-polymorphic regions bounded by unique sequences, and designs PCR
primers within these sequences. The primers can be used to amplify the region
from genomic DNA of any of the species used to create the markers, and the
amplicon size will indicate which species the DNA came from - a SCAR marker.

SCAR markers were defined here:

[bibliography]
- [[[Paran]]], I., and R. W. Michelmore. 'Development of reliable PCR-based markers
linked to downy mildew resistance genes in lettuce.' Theoretical and Applied
Genetics 85.8 (1993): 985-993.

The SCARF software is described in:

[bibliography]
- [[[Toal]]], T., and . 'SCARF: In silico K-mer-based Pipeline Finds Candidate
SCAR Genomic Markers and PCR Primers using NGS Data and Tomato Test Case'
(Publication in process)

*To download and install SCARF, follow the instructions in INSTALL.txt.*

*To run SCARF and generate markers after installing it, follow the instructions in RUN.txt.*

*For help, contact Ted Toal, twtoal@ucdavis.edu*
