IGGPIPE
=======
Ted Toal <twtoal@ucdavis.edu>
Version v0.0, Aug 2015

The BradyLab/IGGPIPE GitHub repository contains code and documentation for the
software package called *IGGPIPE* (*IGG* **P**ipeline).

*IGGPIPE* analyzes two or more genomes
for length-polymorphic regions bounded by unique sequences and designs PCR
primers within these sequences. The primers can be used to amplify the region
from genomic DNA of any of the species used to create the markers, and the
amplicon size will indicate which species the DNA came from - an *IGG* marker.

*IGG* stands for _Indel Group in Genomes_.

Download, Installation, and Running
-----------------------------------

*Requirements*
~~~~~~~~~~~~~~
* The installation instructions are for Mac OSX. For other systems you are on your own,
but please take copious notes and send them to me, and I'll update these instructions.

*Download IGGPIPE files*
~~~~~~~~~~~~~~~~~~~~~~~~
. Browse to https://github.com/BradyLab/IGGPIPE
. At bottom of right column on screen, click "Download ZIP" and choose a place to
put it on your computer.
. Unzip the zip file on your computer.
. Rename the unzipped folder from "IGGPIPE-master" to just "IGGPIPE".

*Install IGGPIPE*
~~~~~~~~~~~~~~~~~
* Look inside the downloaded IGGPIPE folder on your computer for file INSTALL.pdf
or INSTALL.html and open either one and follow the instructions.

*Run IGGPIPE to generate markers after installation*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* Find file RUN.pdf or RUN.html in the IGGPIPE folder on your computer and open
either one and follow the instructions.

*For problems and help:*
~~~~~~~~~~~~~~~~~~~~~~~~
* Post an issue on GitHub under BradyLab/IGGPIPE repository
* Contact me, Ted Toal, twtoal@ucdavis.edu
 
References
----------

.*IGG markers and the IGGPIPE software are described in:*

[bibliography]
- Toal, T.W., Burkart-Waco, D., Kuppu, S., Chetelat, R., and Brady, S.M. 'InDel
Group in Genomes (IGG): Molecular Genetic Markers Between Multiple Species Identified
within Next Generation Sequencing Data by an in silico K-mer-based Pipeline'
(Publication in process)
