RUNNING SCARF TO GENERATE SCAR MARKERS
======================================
Ted Toal <twtoal@ucdavis.edu>

This describes how to run the SCARF software to analyze two or more genome
sequences and produce a file of candidate SCAR marker primer pairs for amplifying
length-polymorphic regions of those genomes.

.*If not done already, download SCARF files:*
. Browse to https://github.com/BradyLab/SCARF
. In upper-left area of screen, find drop-down box Branch:master, click to open it,
and choose the "release" branch.
. At bottom of right column on screen, click "Download ZIP" and choose a place to
put it on your computer.
. Unzip the zip file on your computer.
. Rename the unzipped folder from "SCARF-release" to just "SCARF".

.*If not done already, install SCARF:*
* Look inside the downloaded SCARF folder on your computer for file INSTALL.asciidoc
and open it with a NotePad or TextEdit or other ASCII text editor and follow the
installation instructions.

.*To run SCARF and generate markers:*
. 
