IGGPIPE
=======
Version {VERSION}

The BradyLab/IGGPIPE GitHub repository contains code and documentation for the
software package called *IGGPIPE* (**I**ndel **G**roup in **G**enomes **Pipe**line).

*IGGPIPE* analyzes two or more genomes
for length-polymorphic regions bounded by unique sequences and designs PCR
primers within these sequences. The primers can be used to amplify the region
from genomic DNA of any of the species used to create the markers, and the
amplicon size will indicate which species the DNA came from - an *IGG* marker.

Download, Installation, and Running
-----------------------------------

*Requirements*
~~~~~~~~~~~~~~
* Installation has been tested on 64-bit Mac OSX, 64-bit Linux, and 64-bit Windows.
It will not work on 32-bit systems (due to dependency on Jellyfish2).
* See the INSTALL document section 'Detailed Installation Instructions Part 4:
Install prerequisite applications' for instructions to install these required
programs:
+
--
.. Xcode (V6.4 works) (Apple App Store; 'make' and 'g++')
.. Jellyfish V2 or later (V2.2.3 works) (http://www.genome.umd.edu/jellyfish.html)
.. Perl V5 or later (V5.16.0 works) (https://www.perl.org/get.html)
.. R V3 or later (V3.2.1 works) (https://www.r-project.org)
.. Primer3 (V2.3.6 works) (http://sourceforge.net/projects/primer3)
.. NCBI e-PCR (V2.3.12-1 works) (http://www.ncbi.nlm.nih.gov/tools/epcr)
.. MUSCLE (V3.8.31 works) (http://www.drive5.com/muscle/downloads.htm)
--

*Download IGGPIPE files*
~~~~~~~~~~~~~~~~~~~~~~~~
. Browse to https://github.com/BradyLab/IGGPIPE
. At bottom of right column on screen, click "Download ZIP" and choose a place to
save it on your computer.
+
--
NOTE: Alternatively, you can clone the git repository with this command line command:

  git clone https://github.com/BradyLab/IGGPIPE.git
--
. Unzip the zip file on your computer.
. Rename the unzipped folder from "IGGPIPE-master" to just "IGGPIPE".

*Install IGGPIPE*
~~~~~~~~~~~~~~~~~
* Look inside the downloaded IGGPIPE folder on your computer for file
INSTALL.html, open it, and follow the instructions.

*Run IGGPIPE to generate markers after installation*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* Find file RUN.html in the IGGPIPE folder on your computer, open
it, and follow the instructions.

*For problems and help:*
~~~~~~~~~~~~~~~~~~~~~~~~
* Post an issue on GitHub under BradyLab/IGGPIPE repository
* Contact me, Ted Toal, twtoal@ucdavis.edu

References
----------

.*Please cite the following paper when using IGGPIPE software:*

[bibliography]
- Toal, Ted, Diana Burkart-Waco, Tyson Howell, Mily Ron, Sundaram Kuppu, Anne Bagg
Britt, Roger T. Chetelat, and Siobhan M. Brady.
"Indel Group in Genomes (IGG) Molecular Genetic Markers."
Plant Physiology (2016): pp-00354.
